### ISSUE TITLE
In channel, anyone can move assets at own's disposal

### ISSUE THREAD

**Issue by HyunggyuJang** [ycryptx/recursive-zk-lightning-network#3]
Thus, it has a serious security hole.

**Comment by ycryptx** [comment]
Hey @HyunggyuJang ! First, thanks for taking interest in this project. This is a great catch! An incrementing nonce is the right solution for this security flaw.

By the way, I think the next thing we'd like to do with the ExampleToken contract is to make sure it complies with the Mina token standard. But since that standard doesn't really exist, we should re-evaluate whether the token is implemented as we'd like it to. I just quickly created an ERC-20 like token just for the purpose of demonstration. 

Also, I'd be curious to hear how you heard about this project and how you're planning on using it! Cheers :)

**Comment by ycryptx** [comment]
Very cool! I really liked your hackathon submission, great job 👏 
I'm thinking of continuing researching this project, if you wanna chat more please send me a message on Telegram @yonatan0x!

**Comment by HyunggyuJang** [comment]
> please send me a message on Telegram @yonatan0x

Sent!
